#!/bin/bash

function clean_target {
	RM target/classes/*.class
	RM target/*.jar
}
function build_project {
	javac -cp src -d target/classes src/App.java
}
function package_project {
	jar -cfe target/App.jar App target/classes/*.class
}
function run_project {
	java -cp target/classes/ App
}

case $1 in
clean)
	clean_target
	;;
build)
	build_project
	;;
package)
	package_project
	;;
run)
	run_project
	;;
*)
	clean_target
	build_project
	run_project
	;;
esac
